"use strict";
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Users", [
      {
        id: 1,
        firstName: "Rukshan",
        lastName: "Fernando",
        email: "test@gmail.com",
        password: "123456",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "123 Main Street, Cityville",
        phoneNumber: "+1234567890",
        profilePhoto: "profile1.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 101,
      },
      {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        email: "jane.smith@example.com",
        password: "hashedPassword2",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "456 Oak Avenue, Townsville",
        phoneNumber: "+9876543210",
        profilePhoto: "profile2.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 102,
      },
      {
        id: 3,
        firstName: "Michael",
        lastName: "Johnson",
        email: "michael.johnson@example.com",
        password: "hashedPassword3",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "789 Pine Lane, Villagetown",
        phoneNumber: "+1122334455",
        profilePhoto: "profile3.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 103,
      },
      {
        id: 4,
        firstName: "Emily",
        lastName: "Davis",
        email: "emily.davis@example.com",
        password: "hashedPassword4",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "101 Cedar Street, Hamlet",
        phoneNumber: "+9988776655",
        profilePhoto: "profile4.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 104,
      },
      {
        id: 5,
        firstName: "Christopher",
        lastName: "Martinez",
        email: "christopher.martinez@example.com",
        password: "hashedPassword5",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "202 Maple Drive, Riverside",
        phoneNumber: "+1122334455",
        profilePhoto: "profile5.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 105,
      },
      {
        id: 6,
        firstName: "Olivia",
        lastName: "Taylor",
        email: "olivia.taylor@example.com",
        password: "123456",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "303 Birch Avenue, Hilltop",
        phoneNumber: "+9876543210",
        profilePhoto: "profile6.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 106,
      },
      {
        id: 7,
        firstName: "Daniel",
        lastName: "Brown",
        email: "daniel.brown@example.com",
        password: "hashedPassword7",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "404 Oak Lane, Summit",
        phoneNumber: "+1122334455",
        profilePhoto: "profile7.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 107,
      },
      {
        id: 8,
        firstName: "Sophia",
        lastName: "Clark",
        email: "sophia.clark@example.com",
        password: "hashedPassword8",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "505 Pine Street, Valley",
        phoneNumber: "+9988776655",
        profilePhoto: "profile8.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 108,
      },
      {
        id: 9,
        firstName: "Ethan",
        lastName: "White",
        email: "ethan.white@example.com",
        password: "hashedPassword9",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "606 Cedar Avenue, Ridge",
        phoneNumber: "+9876543210",
        profilePhoto: "profile9.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 109,
      },
      {
        id: 10,
        firstName: "Ava",
        lastName: "Hall",
        email: "ava.hall@example.com",
        password: "hashedPassword10",
        registrationDate: Sequelize.literal("CURRENT_TIMESTAMP"),
        address: "707 Maple Drive, Crest",
        phoneNumber: "+1122334455",
        profilePhoto: "profile10.jpg",
        lastLoging: Sequelize.literal("CURRENT_TIMESTAMP"),
        subscriptionId: 110,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("Users", null, {});
  },
};
