"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Cities", [
      {
        id: 1,
        districtId: 1,
        name_en: "Akkaraipattu",
        name_si: "අක්කරපත්තුව",
        name_ta: "அக்கரைப்பற்று",
      },
      {
        id: 2,
        districtId: 1,
        name_en: "Ampara",
        name_si: "අම්පාර",
        name_ta: "அம்பாறை",
      },
      {
        id: 3,
        districtId: 1,
        name_en: "Deegawapiya",
        name_si: "දීඝවාපිය",
        name_ta: "தீகவாபி",
      },
      {
        id: 4,
        districtId: 1,
        name_en: "Kalmunai",
        name_si: "කල්මුණේ",
        name_ta: "கல்முனை",
      },
      {
        id: 5,
        districtId: 1,
        name_en: "Oluvil",
        name_si: "ඔළුවිල",
        name_ta: "ஒலுவில்",
      },
      {
        id: 6,
        districtId: 1,
        name_en: "Samanthurai",
        name_si: "සමන්තුරේ",
        name_ta: "சம்மாந்துறை",
      },
      {
        id: 7,
        districtId: 2,
        name_en: "Anuradhapura",
        name_si: "අනුරාධපුරය",
        name_ta: "அநுராதபுரம்",
      },
      {
        id: 8,
        districtId: 2,
        name_en: "Kekirawa",
        name_si: "කැකිරාව",
        name_ta: "கெக்கிராவ",
      },
      {
        id: 9,
        districtId: 2,
        name_en: "Mihintale",
        name_si: "මිහින්තලේ",
        name_ta: "மிஹிந்தலை",
      },
      {
        id: 10,
        districtId: 2,
        name_en: "Tambuttegama",
        name_si: "තඹුත්තේගම",
        name_ta: "தம்புத்தேகம",
      },
      {
        id: 11,
        districtId: 2,
        name_en: "Kahatagasdigiliya",
        name_si: "කහටගස්දිගිලිය",
        name_ta: "ககட்டகஸ்திகிலியை",
      },
      {
        id: 12,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 13,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 14,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 15,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 16,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 17,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 18,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 19,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 20,
        districtId: 5,
        name_en: "Colombo 2",
        name_si: "කොළඹ 2",
        name_ta: "கொழும்பு 2",
      },
      {
        id: 21,
        districtId: 5,
        name_en: "Athurugiriya",
        name_si: "අතුරුගිරිය",
        name_ta: "அத்துருகிரிய",
      },
      {
        id: 22,
        districtId: 5,
        name_en: "Avissawella",
        name_si: "අවිස්සාවේල්ල",
        name_ta: "அவிசாவளை",
      },
      {
        id: 23,
        districtId: 5,
        name_en: "Battaramulla",
        name_si: "බත්තරමුල්ල",
        name_ta: "பத்தரமுல்லை",
      },
      {
        id: 24,
        districtId: 5,
        name_en: "Biyagama",
        name_si: "බියගම",
        name_ta: "பியகம",
      },
      {
        id: 25,
        districtId: 5,
        name_en: "Boralesgamuwa",
        name_si: "බොරලැස්ගමුව",
        name_ta: "பொரலெஸ்கமுவ",
      },
      {
        id: 26,
        districtId: 5,
        name_en: "Colombo 8",
        name_si: "කොළඹ 8",
        name_ta: "கொழும்பு 8",
      },
      {
        id: 27,
        districtId: 5,
        name_en: "Dehiwala",
        name_si: "දෙහිවල",
        name_ta: "தெஹிவளை",
      },
      {
        id: 28,
        districtId: 5,
        name_en: "Kaduwela",
        name_si: "කඩුවෙල",
        name_ta: "கடுவெல",
      },
      {
        id: 29,
        districtId: 5,
        name_en: "Maharagama",
        name_si: "මහරගම",
        name_ta: "மகரகம",
      },
      {
        id: 30,
        districtId: 5,
        name_en: "Malabe",
        name_si: "මාළඹේ",
        name_ta: "மாலபே",
      },
      {
        id: 31,
        districtId: 5,
        name_en: "Moratuwa",
        name_si: "මොරටුව",
        name_ta: "மொரட்டுவ",
      },
      {
        id: 32,
        districtId: 5,
        name_en: "Nugegoda",
        name_si: "නුගේගොඩ",
        name_ta: "நுகேகொட",
      },
      {
        id: 33,
        districtId: 5,
        name_en: "Colombo 6",
        name_si: "කොළඹ 6",
        name_ta: "கொழும்பு 6",
      },
      {
        id: 34,
        districtId: 5,
        name_en: "Colombo 13",
        name_si: "කොළඹ 13",
        name_ta: "கொழும்பு 13",
      },
      {
        id: 113,
        districtId: 5,
        name_en: "Kotahena",
        name_si: "කොටහේන",
        name_ta: "கொட்டாஞ்சேன",
      },

      {
        id: 35,
        districtId: 6,
        name_en: "Balapitiya",
        name_si: "බලපිටිය",
        name_ta: "பலபிட்டிய",
      },
      {
        id: 36,
        districtId: 6,
        name_en: "Baddegama",
        name_si: "බද්දේගම",
        name_ta: "பத்தேகம",
      },
      {
        id: 37,
        districtId: 6,
        name_en: "Galle",
        name_si: "ගාල්ල",
        name_ta: "காலி",
      },
      {
        id: 38,
        districtId: 6,
        name_en: "Hikkaduwa",
        name_si: "හික්කඩුව",
        name_ta: "ஹிக்கடுவ",
      },
      {
        id: 39,
        districtId: 6,
        name_en: "Patana",
        name_si: "පතාන",
        name_ta: "பதான",
      },

      {
        id: 40,
        districtId: 7,
        name_en: "Ambepussa",
        name_si: "අඹේපුස්ස",
        name_ta: "அம்பேபுசா",
      },
      {
        id: 41,
        districtId: 7,
        name_en: "Attanagalla",
        name_si: "අත්තනගල්ල",
        name_ta: "அத்தனகல்ல",
      },
      {
        id: 42,
        districtId: 7,
        name_en: "Biyagama IPZ",
        name_si: "බියගම IPZ",
        name_ta: "பியகம IPZ",
      },
      {
        id: 43,
        districtId: 7,
        name_en: "Delgoda",
        name_si: "දෙල්ගොඩ",
        name_ta: "தெல்கொட",
      },
      {
        id: 44,
        districtId: 7,
        name_en: "Divulapitiya",
        name_si: "දිවුලපිටිය",
        name_ta: "திவுலபிட்டிய",
      },
      {
        id: 45,
        districtId: 7,
        name_en: "Gampaha",
        name_si: "ගම්පහ",
        name_ta: "கம்பஹா",
      },
      {
        id: 46,
        districtId: 7,
        name_en: "Ganemulla",
        name_si: "ගණේමුල්ල",
        name_ta: "கணேமுல்லை",
      },
      {
        id: 47,
        districtId: 7,
        name_en: "Ja-Ela",
        name_si: "ජා-ඇල",
        name_ta: "ஜா-எல",
      },
      {
        id: 48,
        districtId: 7,
        name_en: "Kadawatha",
        name_si: "කඩවත",
        name_ta: "கடவதை",
      },
      {
        id: 49,
        districtId: 7,
        name_en: "Katunayake",
        name_si: "කටුනායක",
        name_ta: "கட்டுநாயக்க",
      },
      {
        id: 50,
        districtId: 7,
        name_en: "Kochchikade",
        name_si: "කොච්චිකඩේ",
        name_ta: "கொச்சிக்கடை",
      },
      {
        id: 51,
        districtId: 7,
        name_en: "Mirigama",
        name_si: "මීරිගම",
        name_ta: "மீரிகம",
      },
      {
        id: 52,
        districtId: 7,
        name_en: "Negombo",
        name_si: "මීගමුව",
        name_ta: "நீர்கொழும்பு",
      },
      {
        id: 53,
        districtId: 7,
        name_en: "Nittambuwa",
        name_si: "නිට්ටඹුව",
        name_ta: "நிட்டம்புவ",
      },
      {
        id: 54,
        districtId: 7,
        name_en: "Pasyala",
        name_si: "පස්යාල",
        name_ta: "பஸ்யால'",
      },
      {
        id: 55,
        districtId: 7,
        name_en: "Ragama",
        name_si: "රාගම",
        name_ta: "ராகம",
      },
      {
        id: 56,
        districtId: 7,
        name_en: "Wattala",
        name_si: "වත්තල",
        name_ta: "வத்தளை",
      },
      {
        id: 57,
        districtId: 7,
        name_en: "Yakkala",
        name_si: "යක්කල",
        name_ta: "யக்கல",
      },
      {
        id: 58,
        districtId: 8,
        name_en: "Beliatta",
        name_si: "බෙලිඅත්ත",
        name_ta: "பெலியத்த",
      },
      {
        id: 59,
        districtId: 8,
        name_en: "Hambantota",
        name_si: "හම්බන්තොට",
        name_ta: "ஹம்பாந்தோட்டை",
      },
      {
        id: 60,
        districtId: 8,
        name_en: "Tangalla",
        name_si: "තංගල්ල",
        name_ta: "தங்காலை",
      },
      {
        id: 61,
        districtId: 8,
        name_en: "Tissamaharama",
        name_si: "තිස්සමහාරාම",
        name_ta: "திஸ்ஸமஹராமை",
      },
      {
        id: 62,
        districtId: 8,
        name_en: "Walasmulla",
        name_si: "වළස්මුල්ල",
        name_ta: "வலஸ்முல்ல",
      },
      {
        id: 63,
        districtId: 9,
        name_en: "Jaffna",
        name_si: "යාපනය",
        name_ta: "யாழ்ப்பாணம்",
      },
      {
        id: 64,
        districtId: 10,
        name_en: "Bandaragama",
        name_si: "බණ්ඩාරගම",
        name_ta: "பண்டாரகம",
      },
      {
        id: 65,
        districtId: 10,
        name_en: "Beruwala",
        name_si: "බේරුවල",
        name_ta: "பேருவளை",
      },
      {
        id: 66,
        districtId: 10,
        name_en: "Kahawala",
        name_si: "කහවල",
        name_ta: "கஹவாலா",
      },
      {
        id: 67,
        districtId: 10,
        name_en: "Kalutara",
        name_si: "කළුතර",
        name_ta: "களுத்துறை",
      },
      {
        id: 68,
        districtId: 10,
        name_en: "Matugama",
        name_si: "මතුගම",
        name_ta: "மத்துகம",
      },
      {
        id: 69,
        districtId: 10,
        name_en: "Panadura",
        name_si: "පානදුර",
        name_ta: "பாணந்துறை",
      },
      {
        id: 70,
        districtId: 11,
        name_en: "Deltota",
        name_si: "දෙල්තොට",
        name_ta: "தெல்தொட்ட",
      },
      {
        id: 71,
        districtId: 11,
        name_en: "Gampola",
        name_si: "ගම්පොල",
        name_ta: "கம்பளை",
      },
      {
        id: 72,
        districtId: 11,
        name_en: "Kadugannawa",
        name_si: "කඩුගන්නාව",
        name_ta: "கடுகண்ணாவ",
      },
      {
        id: 73,
        districtId: 11,
        name_en: "Kandy",
        name_si: "මහනුවර",
        name_ta: "கண்டி",
      },
      {
        id: 74,
        districtId: 11,
        name_en: "Katugastota",
        name_si: "කටුගස්තොට",
        name_ta: "கடுகஸ்தோட்டை",
      },
      {
        id: 75,
        districtId: 11,
        name_en: "Pilimatalawa",
        name_si: "පිළිමතලාව",
        name_ta: "பிலிமத்தலாவை",
      },
      {
        id: 76,
        districtId: 11,
        name_en: "Akurana",
        name_si: "අකුරණ",
        name_ta: "அக்குரணை",
      },
      {
        id: 77,
        districtId: 12,
        name_en: "Alawwa",
        name_si: "අලව්ව",
        name_ta: "அலவ்வ",
      },
      {
        id: 78,
        districtId: 12,
        name_en: "Kegalle",
        name_si: "කෑගල්ල",
        name_ta: "கேகாலை",
      },
      {
        id: 79,
        districtId: 12,
        name_en: "Mawanella",
        name_si: "මාවනැල්ල",
        name_ta: "மாவனெல்ல",
      },
      {
        id: 80,
        districtId: 13,
        name_en: "Kilinochchi",
        name_si: "කිළිනොච්චි",
        name_ta: "கிளிநொச்சி",
      },
      {
        id: 81,
        districtId: 14,
        name_en: "Diddeniya",
        name_si: "දෙණියාය",
        name_ta: "தித்தெனிய",
      },
      {
        id: 82,
        districtId: 14,
        name_en: "Kotagala",
        name_si: "කොටගල",
        name_ta: "கொட்டகலை",
      },
      {
        id: 83,
        districtId: 14,
        name_en: "Ibbagamuwa",
        name_si: "ඉබ්බාගමුව",
        name_ta: "இப்பாகமுவ",
      },
      {
        id: 84,
        districtId: 14,
        name_en: "Medirigiriya",
        name_si: "මැදිරිගිරිය",
        name_ta: "மெதிரிகிரிய",
      },
      {
        id: 85,
        districtId: 14,
        name_en: "Melsiripura",
        name_si: "මැල්සිරිපුර",
        name_ta: "மெல்சிரிபுர",
      },
      {
        id: 86,
        districtId: 14,
        name_en: "Polgahawela",
        name_si: "පොල්ගහවෙල",
        name_ta: "பொல்காவெல",
      },
      {
        id: 87,
        districtId: 15,
        name_en: "Mannar",
        name_si: "මන්නාරම",
        name_ta: "மன்னார்",
      },
      {
        id: 88,
        districtId: 16,
        name_en: "Dambulla",
        name_si: "දඹුල්ල",
        name_ta: "தம்புள்ள",
      },
      {
        id: 89,
        districtId: 16,
        name_en: "Galewela",
        name_si: "ගලේවෙල",
        name_ta: "",
      },
      {
        id: 90,
        districtId: 16,
        name_en: "Sigiriya",
        name_si: "සීගිරිය",
        name_ta: "சிகிரியா",
      },
      {
        id: 91,
        districtId: 17,
        name_en: "Akuressa",
        name_si: "අකුරැස්ස",
        name_ta: "அக்குரஸ்ஸை",
      },
      {
        id: 92,
        districtId: 17,
        name_en: "Dikwella",
        name_si: "දික්වැල්ල",
        name_ta: "திக்வெல்ல",
      },
      {
        id: 93,
        districtId: 18,
        name_en: "Kataragama",
        name_si: "කතරගම",
        name_ta: "கதிர்காமம்",
      },
      {
        id: 94,
        districtId: 19,
        name_en: "Mullativu",
        name_si: "මුලතිව්",
        name_ta: "முல்லைத்தீவு",
      },
      {
        id: 95,
        districtId: 20,
        name_en: "Ambewela",
        name_si: "අඹේවෙල",
        name_ta: "அம்பேவெல",
      },
      {
        id: 96,
        districtId: 20,
        name_en: "Hatton",
        name_si: "හැටන්",
        name_ta: "ஹட்டன்",
      },
      {
        id: 97,
        districtId: 20,
        name_en: "Kotmale",
        name_si: "කොත්මලේ",
        name_ta: "கொத்மலை",
      },
      {
        id: 98,
        districtId: 21,
        name_en: "Elahera",
        name_si: "ඇලහැර",
        name_ta: "எலஹெரா",
      },
      {
        id: 99,
        districtId: 21,
        name_en: "Hingurakgoda",
        name_si: "හිඟුරක්ගොඩ",
        name_ta: "இங்குராகொடை",
      },
      {
        id: 100,
        districtId: 21,
        name_en: "Minneriya",
        name_si: "මින්නේරිය",
        name_ta: "மின்னேரியா",
      },
      {
        id: 101,
        districtId: 21,
        name_en: "Polonnaruwa",
        name_si: "පොළොන්නරුව",
        name_ta: "பொலநறுவை",
      },
      {
        id: 102,
        districtId: 22,
        name_en: "Alutgama",
        name_si: "අළුත්ගම",
        name_ta: "அளுத்கம",
      },
      {
        id: 103,
        districtId: 22,
        name_en: "Chilaw",
        name_si: "හලාවත",
        name_ta: "சிலாபம்",
      },
      {
        id: 104,
        districtId: 23,
        name_en: "Kahawatta",
        name_si: "කහවත්ත",
        name_ta: "கஹவத்தை",
      },
      {
        id: 105,
        districtId: 23,
        name_en: "Kuruwita",
        name_si: "කුරුවිට",
        name_ta: "குருவிட்டை",
      },
      {
        id: 106,
        districtId: 24,
        name_en: "Agbopura",
        name_si: "අග්බෝපුර",
        name_ta: "அக்போபுரா",
      },
      {
        id: 107,
        districtId: 24,
        name_en: "China Bay",
        name_si: "චීන වරාය",
        name_ta: "சீன குடா",
      },
      {
        id: 108,
        districtId: 24,
        name_en: "Kanniya",
        name_si: "කන්නියා",
        name_ta: "கிண்ணியா",
      },
      {
        id: 109,
        districtId: 24,
        name_en: "Kantalai",
        name_si: "කන්තලේ",
        name_ta: "கந்தளாய்",
      },
      {
        id: 110,
        districtId: 24,
        name_en: "Seruwila",
        name_si: "සේරුවිල",
        name_ta: "சேருவில",
      },
      {
        id: 111,
        districtId: 24,
        name_en: "Trincomalee",
        name_si: "තිරිකුණාමලය",
        name_ta: "திருகோணமலை",
      },
      {
        id: 112,
        districtId: 25,
        name_en: "Vavuniya",
        name_si: "වව්නියාව",
        name_ta: "வவுனியா",
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("Cities", null, {});
  },
};
